src/Entity/Genre.php
<?php

namespace App\Entity;

use App\Repository\GenreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[UniqueEntity('name')]
#[ORM\Entity(repositoryClass: GenreRepository::class)]
class Genre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 20)]
    #[Assert\Length(min: 1, max: 20 )]
    #[Assert\NotBlank()]
    private ?string $name;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;
    #[Assert\NotBlank()]

    #[ORM\ManyToMany(targetEntity: Anime::class, inversedBy: 'category')]
    private Collection $animes;

    public function __construct()
    {
        $this->animes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    /**
     * @return Collection<int, anime>
     */
    public function getAnimes(): Collection
    {
        return $this->animes;
    }

    public function addAnime(anime $anime): static
    {
        if (!$this->animes->contains($anime)) {
            $this->animes->add($anime);
        }

        return $this;
    }

    public function removeAnime(anime $anime): static
    {
        $this->animes->removeElement($anime);

        return $this;
    }
}

src/Controller/MyHomeController.php
<?php

namespace App\Controller;

use App\Entity\Anime;
use App\Entity\User;
use App\Entity\WatchList;
use App\Repository\WatchListRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


class MyHomeController extends AbstractController
{   
    
    #[Route('/myHome', name: 'myhome.index', methods : ['GET'])]
    
        public function index( Anime $anime,  WatchListRepository $watchListRepository,  WatchList $watchList,User $user, ): Response
        {   
            
            $watchList = $watchListRepository->findOneBy(['user' => $this->getUser()]);
            $watchList->getAnime()->toArray();

        
           
             return $this->render('pages/myhome/myHome.html.twig', [
                'watchList' => $watchList, 
                'anime' => $anime,
                
                'user' => $user,
                
            
            ]);
             
       }

    

       #[Route('/myhome/add/{id}', name: 'watchList.add')]

       public function add($id, Request $request){
        $session = $request->getSession();

        $watchList = $session->get('watchList', []);

        $watchList[$id] = 1;

        $session->set('watchList', $watchList);

        dd($session->get('watchList'));



       }
}

templates/Pages/myhome/myHome.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste d'anime à regarder{% endblock %}

{% block body %}
<div class = "container mt-4">
    <h1 class= "text-5xl text-center mt-24 mb-8">Bienvenue sur votre liste d'animés !</h1>
      <div class="flex flex-row flex-wrap justify-evenly mt-8"><p class = "text-center mt-4"></p>
        <div class="row mt-4">

        {% for anime in watchList.anime %}
   
        <div class="card mt-4">
  
          <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="175" aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
            <rect width="100%" height="100%" fill="#868e96"></rect>
            <text x="50%" y="50%" fill="#dee2e6" dy=".3em">{{anime.name}}</text>
           </svg>
  
  
          <div class="card-body mx-auto"><p>Genre: {{anime.category.name}}</p>
              <p class="card-text">{{anime.description}}</p> 
              <p>Année: {{anime.period}}</p>
          </div>
        </div>
        
        
        
  
        {% endfor %}
       </div>   </div> 
   
   

>   
        
      
    
</div>
<div class="navigation d-flex justify-content-center mt-4">

</div>

{% endblock %}